/**
 * Nombres de icono admitidos en toda la app.
 *
 * Vive en `core/ui` (y no en el componente) para que la capa de datos
 * (`church.config.ts`, `navigation.config.ts`) pueda tipar sus iconos sin
 * depender de la capa de presentación.
 */
export type IconName =
  | 'home'
  | 'users'
  | 'network'
  | 'calendar'
  | 'clock'
  | 'image'
  | 'play'
  | 'map-pin'
  | 'mail'
  | 'phone'
  | 'send'
  | 'copy'
  | 'check'
  | 'gift'
  | 'credit-card'
  | 'share'
  | 'book'
  | 'heart'
  | 'family'
  | 'pray'
  | 'slideshow'
  | 'palette'
  | 'arrow-up'
  | 'whatsapp'
  | 'music'
  | 'church'
  | 'sparkles'
  | 'megaphone'
  | 'trophy'
  | 'download'
  | 'external'
  | 'grip'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'arrow-right'
  | 'menu'
  | 'close'
  | 'fullscreen'
  | 'fullscreen-exit'
  | 'install-app'
  | 'device-desktop'
  | 'device-tablet'
  | 'device-phone'
  | 'share-ios'
  | 'more-vert'
  | 'more-horiz'
  | 'add-box'
  | 'pause'
  | 'zoom-in'
  | 'zoom-out'
  | 'grid'
  | 'maximize'
  | 'rotate-ccw'
  | 'rotate-cw'
  | 'info'
  | 'printer'
  | 'file'
  | 'file-text'
  | 'film'
  | 'fit'
  | 'globe'
  | 'hand-heart'
  | 'mic-vocal'
  | 'flame'
  | 'sprout'
  | 'utensils'
  | 'layout-grid';
